services:
  - type: web
    name: dizipalorijinal
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: DIZPAL_TOKEN
        value: 9iQNC5HQwPlaFuJDkhncJ5XTJ8feGXOJatAA
